development:
  adapter: mysql
  database: mekdigital_blog
  host: 127.0.0.1
  username: root
  password: 
    
production:
  adapter: mysql
  database: mekdigital_blog
  host: mysql.mekdigital.com
  username: etozzato
  password: g-401a